version: '3.3'
services:
    laravel-app:
        build:
            context: .
            dockerfile: ./docker/prod/Dockerfile
        ports:
            - "${DOCKER_EXTERNAL_PORT}:80"
        volumes:
            - ./storage:/var/www/html/storage
        depends_on:
            - redis
        extra_hosts:
            - "host.docker.internal:${DOCKER_LOOPBACK_ADDRESS}"
